# Generated by Django 4.2.11 on 2024-11-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('origin', models.CharField(max_length=200, verbose_name='origin')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
        ),
    ]
